// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account_queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    name,
    phone
)
VALUES (
    $1,
    $2
)
RETURNING id, name, phone, balance, created_at
`

type CreateAccountParams struct {
	Name  string `json:"name"`
	Phone string `json:"phone"`
}

type CreateAccountRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Phone     string             `json:"phone"`
	Balance   int64              `json:"balance"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Name, arg.Phone)
	var i CreateAccountRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const createSettlementAccount = `-- name: CreateSettlementAccount :exec
INSERT INTO accounts (
    name,
    phone,
    is_system
)
SELECT 
    'Settlement Account',
    'SYSTEM',
    TRUE
WHERE NOT EXISTS (
    SELECT 1 
    FROM accounts 
    WHERE is_system = TRUE 
      AND name = 'Settlement Account'
)
`

func (q *Queries) CreateSettlementAccount(ctx context.Context) error {
	_, err := q.db.Exec(ctx, createSettlementAccount)
	return err
}

const deleteAccount = `-- name: DeleteAccount :exec
UPDATE accounts
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DeleteAccount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, name, phone, balance, is_system, created_at, updated_at, deleted_at, mpin_hash
FROM accounts
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Balance,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MpinHash,
	)
	return i, err
}

const getAccountForUpdate = `-- name: GetAccountForUpdate :one
SELECT id, name, phone, balance, is_system, created_at, updated_at, deleted_at, mpin_hash FROM accounts
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) GetAccountForUpdate(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountForUpdate, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Balance,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MpinHash,
	)
	return i, err
}

const getBalance = `-- name: GetBalance :one
SELECT balance
FROM accounts
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBalance(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getBalance, id)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const getMpinHash = `-- name: GetMpinHash :one
SELECT mpin_hash 
FROM accounts 
WHERE id = $1 
LIMIT 1
`

func (q *Queries) GetMpinHash(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getMpinHash, id)
	var mpin_hash string
	err := row.Scan(&mpin_hash)
	return mpin_hash, err
}

const getSettlementAccountForUpdate = `-- name: GetSettlementAccountForUpdate :one
SELECT id, name, phone, balance, is_system, created_at, updated_at, deleted_at, mpin_hash
FROM accounts
WHERE name = 'Settlement Account'
  AND is_system = TRUE
  AND deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) GetSettlementAccountForUpdate(ctx context.Context) (Account, error) {
	row := q.db.QueryRow(ctx, getSettlementAccountForUpdate)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Balance,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MpinHash,
	)
	return i, err
}

const setMpinHash = `-- name: SetMpinHash :exec
UPDATE accounts
SET 
    mpin_hash = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type SetMpinHashParams struct {
	ID       pgtype.UUID `json:"id"`
	MpinHash string      `json:"mpin_hash"`
}

func (q *Queries) SetMpinHash(ctx context.Context, arg SetMpinHashParams) error {
	_, err := q.db.Exec(ctx, setMpinHash, arg.ID, arg.MpinHash)
	return err
}

const updateAccountBalance = `-- name: UpdateAccountBalance :exec
UPDATE accounts 
SET balance = $2, updated_at = NOW() 
WHERE id = $1
`

type UpdateAccountBalanceParams struct {
	ID      pgtype.UUID `json:"id"`
	Balance int64       `json:"balance"`
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error {
	_, err := q.db.Exec(ctx, updateAccountBalance, arg.ID, arg.Balance)
	return err
}
