// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account_queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    name,
    phone,
    mpin_hash
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, name, phone, balance, created_at
`

type CreateAccountParams struct {
	Name     string      `json:"name"`
	Phone    string      `json:"phone"`
	MpinHash pgtype.Text `json:"mpin_hash"`
}

type CreateAccountRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Phone     string             `json:"phone"`
	Balance   int64              `json:"balance"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Name, arg.Phone, arg.MpinHash)
	var i CreateAccountRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const createSettlementAccount = `-- name: CreateSettlementAccount :one
INSERT INTO accounts (
    name,
    phone,
    is_system
)
VALUES (
    'Settlement Account',
    'SYSTEM',
    TRUE
)
ON CONFLICT (is_system) WHERE (is_system = TRUE)
DO UPDATE SET name = EXCLUDED.name
RETURNING id
`

func (q *Queries) CreateSettlementAccount(ctx context.Context) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createSettlementAccount)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteAccount = `-- name: DeleteAccount :exec
UPDATE accounts
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DeleteAccount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const discoverAccountsByPhone = `-- name: DiscoverAccountsByPhone :many
SELECT 
  id
FROM accounts
WHERE phone = $1
`

func (q *Queries) DiscoverAccountsByPhone(ctx context.Context, phone string) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, discoverAccountsByPhone, phone)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, name, phone, balance, is_system, created_at, updated_at, deleted_at, mpin_hash
FROM accounts
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Balance,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MpinHash,
	)
	return i, err
}

const getAccountForUpdate = `-- name: GetAccountForUpdate :one
SELECT id, name, phone, balance, is_system, created_at, updated_at, deleted_at, mpin_hash FROM accounts
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) GetAccountForUpdate(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountForUpdate, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Balance,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MpinHash,
	)
	return i, err
}

const getBalance = `-- name: GetBalance :one
SELECT balance
FROM accounts
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBalance(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getBalance, id)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const getMpinHash = `-- name: GetMpinHash :one
SELECT mpin_hash 
FROM accounts 
WHERE id = $1 
LIMIT 1
`

func (q *Queries) GetMpinHash(ctx context.Context, id pgtype.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getMpinHash, id)
	var mpin_hash pgtype.Text
	err := row.Scan(&mpin_hash)
	return mpin_hash, err
}

const getSettlementAccount = `-- name: GetSettlementAccount :one
SELECT id, name, phone, balance, is_system, created_at, updated_at, deleted_at, mpin_hash
FROM accounts
WHERE name = 'Settlement Account'
  AND is_system = TRUE
  AND deleted_at IS NULL
`

func (q *Queries) GetSettlementAccount(ctx context.Context) (Account, error) {
	row := q.db.QueryRow(ctx, getSettlementAccount)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Balance,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MpinHash,
	)
	return i, err
}

const updateAccountBalanceCredit = `-- name: UpdateAccountBalanceCredit :one
UPDATE accounts 
SET balance = balance + $1, updated_at = NOW() 
WHERE id = $2 
  AND deleted_at IS NULL
RETURNING balance
`

type UpdateAccountBalanceCreditParams struct {
	Balance int64       `json:"balance"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAccountBalanceCredit(ctx context.Context, arg UpdateAccountBalanceCreditParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateAccountBalanceCredit, arg.Balance, arg.ID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const updateMpin = `-- name: UpdateMpin :exec
UPDATE accounts
SET mpin_hash = $2
WHERE id = $1
`

type UpdateMpinParams struct {
	ID       pgtype.UUID `json:"id"`
	MpinHash pgtype.Text `json:"mpin_hash"`
}

func (q *Queries) UpdateMpin(ctx context.Context, arg UpdateMpinParams) error {
	_, err := q.db.Exec(ctx, updateMpin, arg.ID, arg.MpinHash)
	return err
}

const updateSettlementBalanceAtomic = `-- name: UpdateSettlementBalanceAtomic :one
UPDATE accounts 
SET balance = balance + $1, updated_at = NOW() 
WHERE id = $2 AND deleted_at IS NULL
RETURNING balance
`

type UpdateSettlementBalanceAtomicParams struct {
	Balance int64       `json:"balance"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateSettlementBalanceAtomic(ctx context.Context, arg UpdateSettlementBalanceAtomicParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateSettlementBalanceAtomic, arg.Balance, arg.ID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const updateUserBalanceDebit = `-- name: UpdateUserBalanceDebit :one
UPDATE accounts 
SET balance = balance - $1, updated_at = NOW() 
WHERE id = $2 
  AND balance >= $1  
  AND deleted_at IS NULL
RETURNING balance
`

type UpdateUserBalanceDebitParams struct {
	Balance int64       `json:"balance"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserBalanceDebit(ctx context.Context, arg UpdateUserBalanceDebitParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateUserBalanceDebit, arg.Balance, arg.ID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}
