// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_key_queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (
    key_id,
    key_hash,
    client,
    allowed_ips,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING 
    id,
    key_id,
    key_hash,
    client,
    allowed_ips,
    created_at,
    expires_at,
    last_used_at,
    is_active
`

type CreateAPIKeyParams struct {
	KeyID      string             `json:"key_id"`
	KeyHash    string             `json:"key_hash"`
	Client     string             `json:"client"`
	AllowedIps []string           `json:"allowed_ips"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.KeyID,
		arg.KeyHash,
		arg.Client,
		arg.AllowedIps,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.KeyID,
		&i.KeyHash,
		&i.Client,
		&i.AllowedIps,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.IsActive,
	)
	return i, err
}

const deactivateAPIKey = `-- name: DeactivateAPIKey :exec
UPDATE api_keys
SET is_active = FALSE
WHERE key_id = $1
`

func (q *Queries) DeactivateAPIKey(ctx context.Context, keyID string) error {
	_, err := q.db.Exec(ctx, deactivateAPIKey, keyID)
	return err
}

const getAPIKeyByKeyID = `-- name: GetAPIKeyByKeyID :one
SELECT 
    id,
    key_id,
    key_hash,
    client,
    allowed_ips,
    created_at,
    expires_at,
    last_used_at,
    is_active
FROM api_keys
WHERE key_id = $1
LIMIT 1
`

func (q *Queries) GetAPIKeyByKeyID(ctx context.Context, keyID string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByKeyID, keyID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.KeyID,
		&i.KeyHash,
		&i.Client,
		&i.AllowedIps,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.IsActive,
	)
	return i, err
}

const isValid = `-- name: IsValid :one
SELECT EXISTS (
    SELECT 1 FROM api_keys
    WHERE key_id = $1
      AND is_active = TRUE
      AND (expires_at IS NULL OR expires_at > NOW())
)
`

func (q *Queries) IsValid(ctx context.Context, keyID string) (bool, error) {
	row := q.db.QueryRow(ctx, isValid, keyID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys
SET last_used_at = NOW()
WHERE key_id = $1
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, keyID string) error {
	_, err := q.db.Exec(ctx, updateAPIKeyLastUsed, keyID)
	return err
}
