// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger_queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLedgerEntry = `-- name: CreateLedgerEntry :exec
INSERT INTO ledger_entries (
    transaction_id,
    account_id,
    type,
    debit,
    credit,
    balance_after,
    description
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type CreateLedgerEntryParams struct {
	TransactionID pgtype.UUID `json:"transaction_id"`
	AccountID     pgtype.UUID `json:"account_id"`
	Type          string      `json:"type"`
	Debit         int64       `json:"debit"`
	Credit        int64       `json:"credit"`
	BalanceAfter  int64       `json:"balance_after"`
	Description   pgtype.Text `json:"description"`
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, createLedgerEntry,
		arg.TransactionID,
		arg.AccountID,
		arg.Type,
		arg.Debit,
		arg.Credit,
		arg.BalanceAfter,
		arg.Description,
	)
	return err
}
