// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Balance   int64              `json:"balance"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	Phone     string             `json:"phone"`
}

type IdempotencyKey struct {
	Key          string             `json:"key"`
	ResponseCode pgtype.Int4        `json:"response_code"`
	ResponseBody []byte             `json:"response_body"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type LedgerEntry struct {
	ID           pgtype.UUID        `json:"id"`
	AccountID    pgtype.UUID        `json:"account_id"`
	Type         string             `json:"type"`
	Amount       int64              `json:"amount"`
	BalanceAfter int64              `json:"balance_after"`
	Description  pgtype.Text        `json:"description"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Transaction struct {
	ID                  pgtype.UUID        `json:"id"`
	FromAccountID       string             `json:"from_account_id"`
	ToAccountIdentifier string             `json:"to_account_identifier"`
	Amount              int64              `json:"amount"`
	Status              string             `json:"status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}
