// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkIdempotencyKey = `-- name: CheckIdempotencyKey :one
SELECT key, response_code, response_body, created_at FROM idempotency_keys WHERE key = $1
`

func (q *Queries) CheckIdempotencyKey(ctx context.Context, key string) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, checkIdempotencyKey, key)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    name,
    phone
)
VALUES (
    $1,
    $2
)
RETURNING id, name, phone, balance, created_at
`

type CreateAccountParams struct {
	Name  string `json:"name"`
	Phone string `json:"phone"`
}

type CreateAccountRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Phone     string             `json:"phone"`
	Balance   int64              `json:"balance"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Name, arg.Phone)
	var i CreateAccountRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const createLedgerEntry = `-- name: CreateLedgerEntry :exec
INSERT INTO ledger_entries (
    account_id,
    type,
    amount,
    balance_after,
    description
) VALUES (
    $1, $2, $3, $4, $5
)
`

type CreateLedgerEntryParams struct {
	AccountID    pgtype.UUID `json:"account_id"`
	Type         string      `json:"type"`
	Amount       int64       `json:"amount"`
	BalanceAfter int64       `json:"balance_after"`
	Description  pgtype.Text `json:"description"`
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, createLedgerEntry,
		arg.AccountID,
		arg.Type,
		arg.Amount,
		arg.BalanceAfter,
		arg.Description,
	)
	return err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    from_account_id,
    to_account_identifier,
    amount,
    status
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, from_account_id, to_account_identifier, amount, status, created_at, updated_at
`

type CreateTransactionParams struct {
	FromAccountID       string `json:"from_account_id"`
	ToAccountIdentifier string `json:"to_account_identifier"`
	Amount              int64  `json:"amount"`
	Status              string `json:"status"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.FromAccountID,
		arg.ToAccountIdentifier,
		arg.Amount,
		arg.Status,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.FromAccountID,
		&i.ToAccountIdentifier,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
UPDATE accounts
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DeleteAccount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, name, balance, created_at, updated_at, deleted_at, phone
FROM accounts
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Phone,
	)
	return i, err
}

const getAccountForUpdate = `-- name: GetAccountForUpdate :one
SELECT id, name, balance, created_at, updated_at, deleted_at, phone FROM accounts
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) GetAccountForUpdate(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountForUpdate, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Phone,
	)
	return i, err
}

const getBalance = `-- name: GetBalance :one
SELECT balance
FROM accounts
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBalance(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getBalance, id)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const getTransactions = `-- name: GetTransactions :many
SELECT id, from_account_id, to_account_identifier, amount, status, created_at, updated_at
FROM transactions
WHERE from_account_id = $1 or to_account_identifier = $1
ORDER BY created_at DESC
`

func (q *Queries) GetTransactions(ctx context.Context, fromAccountID string) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactions, fromAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.FromAccountID,
			&i.ToAccountIdentifier,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountBalance = `-- name: UpdateAccountBalance :exec
UPDATE accounts
SET balance = $2
WHERE id = $1
`

type UpdateAccountBalanceParams struct {
	ID      pgtype.UUID `json:"id"`
	Balance int64       `json:"balance"`
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error {
	_, err := q.db.Exec(ctx, updateAccountBalance, arg.ID, arg.Balance)
	return err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE transactions
SET status = $2,
    updated_at = NOW()
WHERE id = $1
  AND status != $2
`

type UpdatePaymentStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.Exec(ctx, updatePaymentStatus, arg.ID, arg.Status)
	return err
}
