// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BalanceFromEntries(ctx context.Context, accountID pgtype.UUID) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error)
	CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) error
	CreateSettlementAccount(ctx context.Context) (pgtype.UUID, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	DeactivateAPIKey(ctx context.Context, keyID string) error
	DeleteAccount(ctx context.Context, id pgtype.UUID) error
	DiscoverAccountsByPhone(ctx context.Context, phone string) ([]pgtype.UUID, error)
	GetAPIKeyByKeyID(ctx context.Context, keyID string) (ApiKey, error)
	GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error)
	GetAccountForUpdate(ctx context.Context, id pgtype.UUID) (Account, error)
	GetBalance(ctx context.Context, id pgtype.UUID) (int64, error)
	GetMpinHash(ctx context.Context, id pgtype.UUID) (pgtype.Text, error)
	GetSettlementAccount(ctx context.Context) (Account, error)
	GetTransactionById(ctx context.Context, id pgtype.UUID) (Transaction, error)
	GetTransactionForIdempotency(ctx context.Context, arg GetTransactionForIdempotencyParams) (Transaction, error)
	GetTransactionStatus(ctx context.Context, arg GetTransactionStatusParams) (GetTransactionStatusRow, error)
	GetTransactions(ctx context.Context, fromAccountID string) ([]Transaction, error)
	IsValid(ctx context.Context, keyID string) (bool, error)
	UpdateAPIKeyLastUsed(ctx context.Context, keyID string) error
	UpdateAccountBalanceCredit(ctx context.Context, arg UpdateAccountBalanceCreditParams) (int64, error)
	UpdateMpin(ctx context.Context, arg UpdateMpinParams) error
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error
	UpdateSettlementBalanceAtomic(ctx context.Context, arg UpdateSettlementBalanceAtomicParams) (int64, error)
	UpdateUserBalanceDebit(ctx context.Context, arg UpdateUserBalanceDebitParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
