// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckIdempotencyKey(ctx context.Context, key string) (IdempotencyKey, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error)
	CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) error
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error)
	GetAccountForUpdate(ctx context.Context, id pgtype.UUID) (Account, error)
	GetBalance(ctx context.Context, id pgtype.UUID) (int64, error)
	GetTransactions(ctx context.Context, fromAccountID string) ([]Transaction, error)
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error
}

var _ Querier = (*Queries)(nil)
