// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transaction_queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    from_account_id,
    to_account_identifier,
    amount,
    status
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, from_account_id, to_account_identifier, amount, status, created_at, updated_at
`

type CreateTransactionParams struct {
	FromAccountID       string `json:"from_account_id"`
	ToAccountIdentifier string `json:"to_account_identifier"`
	Amount              int64  `json:"amount"`
	Status              string `json:"status"`
}

type CreateTransactionRow struct {
	ID                  pgtype.UUID        `json:"id"`
	FromAccountID       string             `json:"from_account_id"`
	ToAccountIdentifier string             `json:"to_account_identifier"`
	Amount              int64              `json:"amount"`
	Status              string             `json:"status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.FromAccountID,
		arg.ToAccountIdentifier,
		arg.Amount,
		arg.Status,
	)
	var i CreateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.FromAccountID,
		&i.ToAccountIdentifier,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionById = `-- name: GetTransactionById :one
SELECT id, from_account_id, to_account_identifier, amount, status, created_at, updated_at, external_id 
FROM transactions 
WHERE ID = $1
`

func (q *Queries) GetTransactionById(ctx context.Context, id pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionById, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.FromAccountID,
		&i.ToAccountIdentifier,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalID,
	)
	return i, err
}

const getTransactions = `-- name: GetTransactions :many
SELECT id, from_account_id, to_account_identifier, amount, status, created_at, updated_at, external_id
FROM transactions
WHERE from_account_id = $1 or to_account_identifier = $1
ORDER BY created_at DESC
`

func (q *Queries) GetTransactions(ctx context.Context, fromAccountID string) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactions, fromAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.FromAccountID,
			&i.ToAccountIdentifier,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExternalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE transactions
SET status = $2,
    updated_at = NOW()
WHERE id = $1
  AND status != $2
`

type UpdatePaymentStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.Exec(ctx, updatePaymentStatus, arg.ID, arg.Status)
	return err
}
