// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transaction_queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    from_account_id,
    to_account_identifier,
    amount,
    status,
    external_id,
    type
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, from_account_id, to_account_identifier, amount, status, created_at, updated_at, external_id, type
`

type CreateTransactionParams struct {
	FromAccountID       string `json:"from_account_id"`
	ToAccountIdentifier string `json:"to_account_identifier"`
	Amount              int64  `json:"amount"`
	Status              string `json:"status"`
	ExternalID          string `json:"external_id"`
	Type                string `json:"type"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.FromAccountID,
		arg.ToAccountIdentifier,
		arg.Amount,
		arg.Status,
		arg.ExternalID,
		arg.Type,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.FromAccountID,
		&i.ToAccountIdentifier,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalID,
		&i.Type,
	)
	return i, err
}

const getTransactionById = `-- name: GetTransactionById :one
SELECT id, from_account_id, to_account_identifier, amount, status, created_at, updated_at, external_id, type 
FROM transactions 
WHERE ID = $1
`

func (q *Queries) GetTransactionById(ctx context.Context, id pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionById, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.FromAccountID,
		&i.ToAccountIdentifier,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalID,
		&i.Type,
	)
	return i, err
}

const getTransactionForIdempotency = `-- name: GetTransactionForIdempotency :one
SELECT id, from_account_id, to_account_identifier, amount, status, created_at, updated_at, external_id, type 
FROM transactions 
WHERE external_id = $1 AND type = $2
`

type GetTransactionForIdempotencyParams struct {
	ExternalID string `json:"external_id"`
	Type       string `json:"type"`
}

func (q *Queries) GetTransactionForIdempotency(ctx context.Context, arg GetTransactionForIdempotencyParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionForIdempotency, arg.ExternalID, arg.Type)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.FromAccountID,
		&i.ToAccountIdentifier,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalID,
		&i.Type,
	)
	return i, err
}

const getTransactionStatus = `-- name: GetTransactionStatus :one
SELECT Status, ID
FROM transactions 
WHERE external_id = $1 AND type = $2
`

type GetTransactionStatusParams struct {
	ExternalID string `json:"external_id"`
	Type       string `json:"type"`
}

type GetTransactionStatusRow struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) GetTransactionStatus(ctx context.Context, arg GetTransactionStatusParams) (GetTransactionStatusRow, error) {
	row := q.db.QueryRow(ctx, getTransactionStatus, arg.ExternalID, arg.Type)
	var i GetTransactionStatusRow
	err := row.Scan(&i.Status, &i.ID)
	return i, err
}

const getTransactions = `-- name: GetTransactions :many
SELECT id, from_account_id, to_account_identifier, amount, status, created_at, updated_at, external_id, type
FROM transactions
WHERE from_account_id = $1 or to_account_identifier = $1
ORDER BY created_at DESC
`

func (q *Queries) GetTransactions(ctx context.Context, fromAccountID string) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactions, fromAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.FromAccountID,
			&i.ToAccountIdentifier,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExternalID,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE transactions
SET status = $2,
    updated_at = NOW()
WHERE id = $1
  AND status != $2
`

type UpdatePaymentStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.Exec(ctx, updatePaymentStatus, arg.ID, arg.Status)
	return err
}
