// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	Phone     string           `json:"phone"`
	Balance   int64            `json:"balance"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Transaction struct {
	ID        string           `json:"id"`
	AccountID string           `json:"account_id"`
	Type      string           `json:"type"`
	Amount    int64            `json:"amount"`
	Status    string           `json:"status"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
