// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CheckBalance(ctx context.Context, id string) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	GetAccountByID(ctx context.Context, id string) (Account, error)
	GetAccountForUpdate(ctx context.Context, id string) (Account, error)
	GetTransactions(ctx context.Context, accountID string) ([]Transaction, error)
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error
}

var _ Querier = (*Queries)(nil)
