// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"
)

const checkBalance = `-- name: CheckBalance :one
SELECT balance
FROM accounts
WHERE id = $1
`

func (q *Queries) CheckBalance(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRow(ctx, checkBalance, id)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    id,
    name,
    phone,
    balance
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, name, phone, balance, created_at
`

type CreateAccountParams struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Phone   string `json:"phone"`
	Balance int64  `json:"balance"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.Balance,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    id,
    account_id,
    type,
    amount,
    status,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    NOW()
)
RETURNING id, account_id, type, amount, status, created_at
`

type CreateTransactionParams struct {
	ID        string `json:"id"`
	AccountID string `json:"account_id"`
	Type      string `json:"type"`
	Amount    int64  `json:"amount"`
	Status    string `json:"status"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.ID,
		arg.AccountID,
		arg.Type,
		arg.Amount,
		arg.Status,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Type,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, name, phone, balance, created_at
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountForUpdate = `-- name: GetAccountForUpdate :one
SELECT id, name, phone, balance, created_at FROM accounts
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetAccountForUpdate(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountForUpdate, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactions = `-- name: GetTransactions :many
SELECT 
    id,
    account_id,
    type,
    amount,
    status,
    created_at
FROM transactions
WHERE account_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetTransactions(ctx context.Context, accountID string) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactions, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Type,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountBalance = `-- name: UpdateAccountBalance :exec
UPDATE accounts
SET balance = $2
WHERE id = $1
`

type UpdateAccountBalanceParams struct {
	ID      string `json:"id"`
	Balance int64  `json:"balance"`
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error {
	_, err := q.db.Exec(ctx, updateAccountBalance, arg.ID, arg.Balance)
	return err
}
