services:
  postgres:
    image: postgres:16-alpine
    container_name: npci-switch-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: npci-switch
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


  redis:
    image: redis:7
    container_name: npci-redis
    restart: always
    ports:
      - "6379:6379"


volumes:
  postgres-data: