// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type TransactionState string

const (
	TransactionStateINITIATED     TransactionState = "INITIATED"
	TransactionStateDEBITPENDING  TransactionState = "DEBIT_PENDING"
	TransactionStateDEBITSUCCESS  TransactionState = "DEBIT_SUCCESS"
	TransactionStateDEBITFAILED   TransactionState = "DEBIT_FAILED"
	TransactionStateCREDITPENDING TransactionState = "CREDIT_PENDING"
	TransactionStateCREDITSUCCESS TransactionState = "CREDIT_SUCCESS"
	TransactionStateCREDITFAILED  TransactionState = "CREDIT_FAILED"
	TransactionStateSUCCESSFAILED TransactionState = "SUCCESSFAILED"
	TransactionStateREVERSED      TransactionState = "REVERSED"
)

func (e *TransactionState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionState(s)
	case string:
		*e = TransactionState(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionState: %T", src)
	}
	return nil
}

type NullTransactionState struct {
	TransactionState TransactionState `json:"transaction_state"`
	Valid            bool             `json:"valid"` // Valid is true if TransactionState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionState) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionState), nil
}

type Transaction struct {
	ID          pgtype.UUID        `json:"id"`
	PayerVpa    string             `json:"payer_vpa"`
	PayerBank   string             `json:"payer_bank"`
	PayeeVpa    string             `json:"payee_vpa"`
	PayeeBank   string             `json:"payee_bank"`
	Amount      int64              `json:"amount"`
	State       TransactionState   `json:"state"`
	ReferenceID pgtype.Text        `json:"reference_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
