// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	GetTransaction(ctx context.Context, id pgtype.UUID) (Transaction, error)
	GetTransactionByReference(ctx context.Context, referenceID pgtype.Text) (Transaction, error)
	UpdateTransactionState(ctx context.Context, arg UpdateTransactionStateParams) (Transaction, error)
}

var _ Querier = (*Queries)(nil)
