// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    id,
    payer_vpa,
    payer_bank,
    payee_vpa,
    payee_bank,
    amount,
    state,
    reference_id
) VALUES (
    $1,$2,$3,$4,$5,$6,$7,$8
)
RETURNING id, payer_vpa, payer_bank, payee_vpa, payee_bank, amount, state, reference_id, created_at, updated_at
`

type CreateTransactionParams struct {
	ID          pgtype.UUID      `json:"id"`
	PayerVpa    string           `json:"payer_vpa"`
	PayerBank   string           `json:"payer_bank"`
	PayeeVpa    string           `json:"payee_vpa"`
	PayeeBank   string           `json:"payee_bank"`
	Amount      int64            `json:"amount"`
	State       TransactionState `json:"state"`
	ReferenceID pgtype.Text      `json:"reference_id"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.ID,
		arg.PayerVpa,
		arg.PayerBank,
		arg.PayeeVpa,
		arg.PayeeBank,
		arg.Amount,
		arg.State,
		arg.ReferenceID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.PayerVpa,
		&i.PayerBank,
		&i.PayeeVpa,
		&i.PayeeBank,
		&i.Amount,
		&i.State,
		&i.ReferenceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, payer_vpa, payer_bank, payee_vpa, payee_bank, amount, state, reference_id, created_at, updated_at FROM transactions
WHERE id = $1
`

func (q *Queries) GetTransaction(ctx context.Context, id pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.PayerVpa,
		&i.PayerBank,
		&i.PayeeVpa,
		&i.PayeeBank,
		&i.Amount,
		&i.State,
		&i.ReferenceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionByReference = `-- name: GetTransactionByReference :one
SELECT id, payer_vpa, payer_bank, payee_vpa, payee_bank, amount, state, reference_id, created_at, updated_at FROM transactions
WHERE reference_id = $1
`

func (q *Queries) GetTransactionByReference(ctx context.Context, referenceID pgtype.Text) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByReference, referenceID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.PayerVpa,
		&i.PayerBank,
		&i.PayeeVpa,
		&i.PayeeBank,
		&i.Amount,
		&i.State,
		&i.ReferenceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTransactionState = `-- name: UpdateTransactionState :one
UPDATE transactions
SET state = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, payer_vpa, payer_bank, payee_vpa, payee_bank, amount, state, reference_id, created_at, updated_at
`

type UpdateTransactionStateParams struct {
	ID    pgtype.UUID      `json:"id"`
	State TransactionState `json:"state"`
}

func (q *Queries) UpdateTransactionState(ctx context.Context, arg UpdateTransactionStateParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransactionState, arg.ID, arg.State)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.PayerVpa,
		&i.PayerBank,
		&i.PayeeVpa,
		&i.PayeeBank,
		&i.Amount,
		&i.State,
		&i.ReferenceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
